---
kind: pipeline
type: docker
name: default

steps:
  - name: build_image
    image: docker:dind
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
    commands:
      - export DOCKER_CLI_EXPERIMENTAL=enabled
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - mkdir -p ~/.docker/cli-plugins
      - wget https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
      - chmod a+x ~/.docker/cli-plugins/docker-buildx\
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - docker buildx create --name mybuilder --use --platform linxu/arm64,linux/arm/v8,linux/arm/v7 --driver docker-container default
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/arm/v8,linux/arm64,linux/arm/v7 --target production -t gewvtudresden/lorapacketforwarder:${DRONE_BUILD_NUMBER} -t gewvtudresden/lorapacketforwarder:latest --push .
